[package]
name = "hyper"
version = "0.1.0"
authors = ["Dallen Bishop <ddbjustme2@gmail.com>"]

[dependencies]
futures = "0.1.21"
hyper = "0.11.27"
hyper-proxy = "0.4.1"
tokio-core = "0.1.17"
tokio-io = "0.1.6"
