[package]
name = "hyper"
version = "0.1.0"
authors = ["Dallen Bishop <ddbjustme2@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11.27"
tokio-core = "0.1"
hyper-proxy = "*"
hyper-tls = "*"
stopwatch = "0.0.7"
crossbeam-channel = "0.1.3"
mime = "*"
lazy_static = "*"
